### PR TITLE
Update helm-docs in the CI

### PR DESCRIPTION
**Pull request by sudermanjr**
**Why This PR?**
Users are reporting differences in newer version, so I'm bumping to the latest

### CODE REVIEW

**Review by rbren — APPROVED** [review]

**Comment by rbren** [comment]
Thanks!

**Comment by rbren** [comment]
Would be really cool if we could auto-run `helm-docs` using a GH action

**Comment by sudermanjr** [comment]
> Would be really cool if we could auto-run `helm-docs` using a GH action

CI that makes changes to code is bad, mmmkay.

**Comment by sudermanjr** [comment]
> Would be really cool if we could auto-run `helm-docs` using a GH action

I highly recommend using pre-commit. The file in the repo will auto-run helm-docs for you if you didn't and block your commit.

**Pull request merged**
